### ISSUE TITLE
canal_protocol.py是怎么得到的呢

### ISSUE THREAD

**Issue by gitligl** [hiro93/canal-py#1]
小白请教一下作者：python接口文件canal_protocol.py是通过protoc工具生成的，还是结合CanalProtocol.proto手动写的呢？为什么我通过protoc工具生成的CanalProtocol_pb2.py文件与这个差别非常大，完全不知道该怎么用

**Comment by hiro93** [comment]
我是用 https://github.com/Pr0Ger/protobuf3 手写的，因为觉得protoc编译出来的比较丑，理论上应该作用是一样的。
